// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';
import {services} from '../models';

export function AddSongsToFavorite(arg1:string,arg2:Array<string>):Promise<models.FavoriteSummary>;

export function ApplyLyricCandidate(arg1:string,arg2:string):Promise<models.LyricView>;

export function ClearAudioCache():Promise<void>;

export function ClearLibrary():Promise<void>;

export function CreateLocalFavorite(arg1:string):Promise<models.FavoriteSummary>;

export function CreateStreamSource(arg1:string,arg2:string,arg3:time.Time):Promise<string>;

export function CreateTheme(arg1:models.Theme):Promise<models.Theme>;

export function DeleteActiveLyric(arg1:string):Promise<models.LyricView>;

export function DeleteDownloadedSong(arg1:string):Promise<void>;

export function DeleteFavorite(arg1:string):Promise<void>;

export function DeleteSong(arg1:string):Promise<void>;

export function DeleteTheme(arg1:string):Promise<void>;

export function DeleteUnreferencedSongs():Promise<number>;

export function DetachFavoriteSource(arg1:string,arg2:boolean):Promise<models.Favorite>;

export function DownloadSong(arg1:string):Promise<string>;

export function DuplicateFavorite(arg1:string,arg2:string):Promise<models.FavoriteSummary>;

export function EnsureAudioProxyRunning():Promise<string>;

export function ExportData():Promise<services.ExportData>;

export function GenerateLoginQR():Promise<services.QRCodeResponse>;

export function GetActiveLyric(arg1:string):Promise<models.LyricView>;

export function GetAudioCacheID(arg1:string):Promise<string>;

export function GetAudioCacheSize():Promise<number>;

export function GetBiliFavoriteImportTask(arg1:string):Promise<models.BiliFavoriteImportTask>;

export function GetDownloadedSongIDs(arg1:Array<string>):Promise<Array<string>>;

export function GetFavoriteCollectionBVIDs(arg1:number):Promise<Array<models.BiliFavoriteInfo>>;

export function GetFavoriteCollectionInfo(arg1:number):Promise<models.BiliFavoriteCollection>;

export function GetFavoriteMemberships(arg1:string):Promise<Array<string>>;

export function GetFavoriteSyncStatus(arg1:string):Promise<models.PlaylistSyncStatus>;

export function GetFavoriteSyncTask(arg1:string):Promise<models.FavoriteSyncTask>;

export function GetImageProxyURL(arg1:string):Promise<string>;

export function GetLocalAudioURL(arg1:string):Promise<string>;

export function GetLyricMapping(arg1:string):Promise<models.LyricMapping>;

export function GetLyricSearch(arg1:string):Promise<models.LyricSearchTask>;

export function GetMyFavoriteCollections():Promise<Array<models.BiliFavoriteCollection>>;

export function GetPlayHistory():Promise<services.PlayHistory>;

export function GetPlayURL(arg1:string,arg2:number):Promise<services.PlayInfo>;

export function GetPlayerSetting():Promise<models.PlayerSetting>;

export function GetPlaylist():Promise<models.Playlist>;

export function GetProxyBaseURL():Promise<string>;

export function GetSongsByIDs(arg1:Array<string>):Promise<Array<models.Song>>;

export function GetThemes():Promise<Array<models.Theme>>;

export function GetUserInfo():Promise<services.UserInfo>;

export function ImportBiliFavorite(arg1:models.BiliFavoriteImportRequest):Promise<models.BiliFavoriteImportResult>;

export function ImportData(arg1:services.ExportData):Promise<void>;

export function ImportLyricFile(arg1:string,arg2:Array<number>,arg3:string):Promise<models.LyricView>;

export function ImportLyricText(arg1:string,arg2:string,arg3:string):Promise<models.LyricView>;

export function IsLoggedIn():Promise<boolean>;

export function IsSongDownloaded(arg1:string):Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function ListFavoriteSongs(arg1:models.FavoriteSongPageRequest):Promise<models.FavoriteSongPage>;

export function ListFavoriteSummaries():Promise<Array<models.FavoriteSummary>>;

export function ListFavorites():Promise<Array<models.Favorite>>;

export function ListSongs():Promise<Array<models.Song>>;

export function Logout():Promise<void>;

export function MaximizeWindow():Promise<void>;

export function MigrateLegacyLyrics():Promise<void>;

export function MinimiseWindow():Promise<void>;

export function MinimizeToTray():Promise<void>;

export function OpenAudioCacheFolder():Promise<void>;

export function OpenDatabaseFile():Promise<void>;

export function OpenDownloadedFile(arg1:string):Promise<void>;

export function OpenDownloadsFolder():Promise<void>;

export function PollLogin(arg1:string):Promise<services.LoginPollResponse>;

export function PreviewLyricFile(arg1:Array<number>,arg2:string,arg3:number):Promise<models.LyricImportPreview>;

export function PreviewLyricText(arg1:string,arg2:string,arg3:number):Promise<models.LyricImportPreview>;

export function QuitApp():Promise<void>;

export function RecoverInterruptedPlaylistSyncs():Promise<void>;

export function RefreshProxyURL(arg1:string):Promise<string>;

export function RejectLyricCandidate(arg1:string,arg2:string):Promise<models.LyricView>;

export function RemoveSongFromFavorite(arg1:string,arg2:string):Promise<models.FavoriteSummary>;

export function RenameFavorite(arg1:string,arg2:string):Promise<models.FavoriteSummary>;

export function ResolveBiliAudio(arg1:string):Promise<models.BiliAudio>;

export function RestoreAutomaticLyric(arg1:string):Promise<models.LyricView>;

export function SaveFavorite(arg1:models.Favorite):Promise<void>;

export function SaveLyricMapping(arg1:models.LyricMapping):Promise<void>;

export function SaveManualLyric(arg1:string,arg2:string,arg3:string):Promise<models.LyricView>;

export function SavePlayHistory(arg1:string,arg2:string):Promise<void>;

export function SavePlayerSetting(arg1:models.PlayerSetting):Promise<void>;

export function SavePlaylist(arg1:string,arg2:number):Promise<void>;

export function SaveThemeImageFromDataURL(arg1:string):Promise<string>;

export function SaveThemeImageFromURL(arg1:string):Promise<string>;

export function SearchBVID(arg1:string):Promise<Array<models.Song>>;

export function SearchBiliVideos(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<models.Song>>;

export function SearchLocalSongPage(arg1:models.LocalSongSearchRequest):Promise<models.LocalSongSearchPage>;

export function SearchLocalSongs(arg1:string):Promise<Array<models.Song>>;

export function SearchLyrics(arg1:models.LyricSearchRequest):Promise<models.LyricSearchTask>;

export function Seed():Promise<void>;

export function SetCurrentTheme(arg1:string):Promise<void>;

export function SetLyricOffset(arg1:string,arg2:number):Promise<models.LyricView>;

export function StartBiliFavoriteImport(arg1:models.BiliFavoriteImportRequest):Promise<models.BiliFavoriteImportTask>;

export function SyncFavorite(arg1:string,arg2:boolean):Promise<models.FavoriteSyncTask>;

export function SyncStaleBiliFavorites(arg1:number):Promise<Array<models.PlaylistSyncStatus>>;

export function UnmaximizeWindow():Promise<void>;

export function UpdateTheme(arg1:models.Theme):Promise<void>;

export function UpsertSongs(arg1:Array<models.Song>):Promise<void>;

export function UpsertSongsAndReturn(arg1:Array<models.Song>):Promise<Array<models.Song>>;
