// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLyricCandidate(arg1, arg2) {
  return window['go']['services']['Service']['ApplyLyricCandidate'](arg1, arg2);
}

export function ClearAudioCache() {
  return window['go']['services']['Service']['ClearAudioCache']();
}

export function ClearLibrary() {
  return window['go']['services']['Service']['ClearLibrary']();
}

export function CreateStreamSource(arg1, arg2, arg3) {
  return window['go']['services']['Service']['CreateStreamSource'](arg1, arg2, arg3);
}

export function CreateTheme(arg1) {
  return window['go']['services']['Service']['CreateTheme'](arg1);
}

export function DeleteActiveLyric(arg1) {
  return window['go']['services']['Service']['DeleteActiveLyric'](arg1);
}

export function DeleteDownloadedSong(arg1) {
  return window['go']['services']['Service']['DeleteDownloadedSong'](arg1);
}

export function DeleteFavorite(arg1) {
  return window['go']['services']['Service']['DeleteFavorite'](arg1);
}

export function DeleteSong(arg1) {
  return window['go']['services']['Service']['DeleteSong'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['services']['Service']['DeleteTheme'](arg1);
}

export function DeleteUnreferencedSongs() {
  return window['go']['services']['Service']['DeleteUnreferencedSongs']();
}

export function DetachFavoriteSource(arg1, arg2) {
  return window['go']['services']['Service']['DetachFavoriteSource'](arg1, arg2);
}

export function DownloadSong(arg1) {
  return window['go']['services']['Service']['DownloadSong'](arg1);
}

export function EnsureAudioProxyRunning() {
  return window['go']['services']['Service']['EnsureAudioProxyRunning']();
}

export function ExportData() {
  return window['go']['services']['Service']['ExportData']();
}

export function GenerateLoginQR() {
  return window['go']['services']['Service']['GenerateLoginQR']();
}

export function GetActiveLyric(arg1) {
  return window['go']['services']['Service']['GetActiveLyric'](arg1);
}

export function GetAudioCacheID(arg1) {
  return window['go']['services']['Service']['GetAudioCacheID'](arg1);
}

export function GetAudioCacheSize() {
  return window['go']['services']['Service']['GetAudioCacheSize']();
}

export function GetDownloadedSongIDs(arg1) {
  return window['go']['services']['Service']['GetDownloadedSongIDs'](arg1);
}

export function GetFavoriteCollectionBVIDs(arg1) {
  return window['go']['services']['Service']['GetFavoriteCollectionBVIDs'](arg1);
}

export function GetFavoriteCollectionInfo(arg1) {
  return window['go']['services']['Service']['GetFavoriteCollectionInfo'](arg1);
}

export function GetFavoriteSyncStatus(arg1) {
  return window['go']['services']['Service']['GetFavoriteSyncStatus'](arg1);
}

export function GetFavoriteSyncTask(arg1) {
  return window['go']['services']['Service']['GetFavoriteSyncTask'](arg1);
}

export function GetImageProxyURL(arg1) {
  return window['go']['services']['Service']['GetImageProxyURL'](arg1);
}

export function GetLocalAudioURL(arg1) {
  return window['go']['services']['Service']['GetLocalAudioURL'](arg1);
}

export function GetLyricMapping(arg1) {
  return window['go']['services']['Service']['GetLyricMapping'](arg1);
}

export function GetLyricSearch(arg1) {
  return window['go']['services']['Service']['GetLyricSearch'](arg1);
}

export function GetMyFavoriteCollections() {
  return window['go']['services']['Service']['GetMyFavoriteCollections']();
}

export function GetPlayHistory() {
  return window['go']['services']['Service']['GetPlayHistory']();
}

export function GetPlayURL(arg1, arg2) {
  return window['go']['services']['Service']['GetPlayURL'](arg1, arg2);
}

export function GetPlayerSetting() {
  return window['go']['services']['Service']['GetPlayerSetting']();
}

export function GetPlaylist() {
  return window['go']['services']['Service']['GetPlaylist']();
}

export function GetProxyBaseURL() {
  return window['go']['services']['Service']['GetProxyBaseURL']();
}

export function GetThemes() {
  return window['go']['services']['Service']['GetThemes']();
}

export function GetUserInfo() {
  return window['go']['services']['Service']['GetUserInfo']();
}

export function ImportBiliFavorite(arg1) {
  return window['go']['services']['Service']['ImportBiliFavorite'](arg1);
}

export function ImportData(arg1) {
  return window['go']['services']['Service']['ImportData'](arg1);
}

export function ImportLyricFile(arg1, arg2, arg3) {
  return window['go']['services']['Service']['ImportLyricFile'](arg1, arg2, arg3);
}

export function ImportLyricText(arg1, arg2, arg3) {
  return window['go']['services']['Service']['ImportLyricText'](arg1, arg2, arg3);
}

export function IsLoggedIn() {
  return window['go']['services']['Service']['IsLoggedIn']();
}

export function IsSongDownloaded(arg1) {
  return window['go']['services']['Service']['IsSongDownloaded'](arg1);
}

export function IsWindowMaximized() {
  return window['go']['services']['Service']['IsWindowMaximized']();
}

export function ListFavorites() {
  return window['go']['services']['Service']['ListFavorites']();
}

export function ListSongs() {
  return window['go']['services']['Service']['ListSongs']();
}

export function Logout() {
  return window['go']['services']['Service']['Logout']();
}

export function MaximizeWindow() {
  return window['go']['services']['Service']['MaximizeWindow']();
}

export function MigrateLegacyLyrics() {
  return window['go']['services']['Service']['MigrateLegacyLyrics']();
}

export function MinimiseWindow() {
  return window['go']['services']['Service']['MinimiseWindow']();
}

export function MinimizeToTray() {
  return window['go']['services']['Service']['MinimizeToTray']();
}

export function OpenAudioCacheFolder() {
  return window['go']['services']['Service']['OpenAudioCacheFolder']();
}

export function OpenDatabaseFile() {
  return window['go']['services']['Service']['OpenDatabaseFile']();
}

export function OpenDownloadedFile(arg1) {
  return window['go']['services']['Service']['OpenDownloadedFile'](arg1);
}

export function OpenDownloadsFolder() {
  return window['go']['services']['Service']['OpenDownloadsFolder']();
}

export function PollLogin(arg1) {
  return window['go']['services']['Service']['PollLogin'](arg1);
}

export function PreviewLyricFile(arg1, arg2, arg3) {
  return window['go']['services']['Service']['PreviewLyricFile'](arg1, arg2, arg3);
}

export function PreviewLyricText(arg1, arg2, arg3) {
  return window['go']['services']['Service']['PreviewLyricText'](arg1, arg2, arg3);
}

export function QuitApp() {
  return window['go']['services']['Service']['QuitApp']();
}

export function RecoverInterruptedPlaylistSyncs() {
  return window['go']['services']['Service']['RecoverInterruptedPlaylistSyncs']();
}

export function RefreshProxyURL(arg1) {
  return window['go']['services']['Service']['RefreshProxyURL'](arg1);
}

export function RejectLyricCandidate(arg1, arg2) {
  return window['go']['services']['Service']['RejectLyricCandidate'](arg1, arg2);
}

export function ResolveBiliAudio(arg1) {
  return window['go']['services']['Service']['ResolveBiliAudio'](arg1);
}

export function RestoreAutomaticLyric(arg1) {
  return window['go']['services']['Service']['RestoreAutomaticLyric'](arg1);
}

export function SaveFavorite(arg1) {
  return window['go']['services']['Service']['SaveFavorite'](arg1);
}

export function SaveLyricMapping(arg1) {
  return window['go']['services']['Service']['SaveLyricMapping'](arg1);
}

export function SaveManualLyric(arg1, arg2, arg3) {
  return window['go']['services']['Service']['SaveManualLyric'](arg1, arg2, arg3);
}

export function SavePlayHistory(arg1, arg2) {
  return window['go']['services']['Service']['SavePlayHistory'](arg1, arg2);
}

export function SavePlayerSetting(arg1) {
  return window['go']['services']['Service']['SavePlayerSetting'](arg1);
}

export function SavePlaylist(arg1, arg2) {
  return window['go']['services']['Service']['SavePlaylist'](arg1, arg2);
}

export function SaveThemeImageFromDataURL(arg1) {
  return window['go']['services']['Service']['SaveThemeImageFromDataURL'](arg1);
}

export function SaveThemeImageFromURL(arg1) {
  return window['go']['services']['Service']['SaveThemeImageFromURL'](arg1);
}

export function SearchBVID(arg1) {
  return window['go']['services']['Service']['SearchBVID'](arg1);
}

export function SearchBiliVideos(arg1, arg2, arg3, arg4) {
  return window['go']['services']['Service']['SearchBiliVideos'](arg1, arg2, arg3, arg4);
}

export function SearchLocalSongs(arg1) {
  return window['go']['services']['Service']['SearchLocalSongs'](arg1);
}

export function SearchLyrics(arg1) {
  return window['go']['services']['Service']['SearchLyrics'](arg1);
}

export function Seed() {
  return window['go']['services']['Service']['Seed']();
}

export function SetCurrentTheme(arg1) {
  return window['go']['services']['Service']['SetCurrentTheme'](arg1);
}

export function SetLyricOffset(arg1, arg2) {
  return window['go']['services']['Service']['SetLyricOffset'](arg1, arg2);
}

export function SyncFavorite(arg1, arg2) {
  return window['go']['services']['Service']['SyncFavorite'](arg1, arg2);
}

export function SyncStaleBiliFavorites(arg1) {
  return window['go']['services']['Service']['SyncStaleBiliFavorites'](arg1);
}

export function UnmaximizeWindow() {
  return window['go']['services']['Service']['UnmaximizeWindow']();
}

export function UpdateTheme(arg1) {
  return window['go']['services']['Service']['UpdateTheme'](arg1);
}

export function UpsertSongs(arg1) {
  return window['go']['services']['Service']['UpsertSongs'](arg1);
}
