// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {models} from '../models';
import {services} from '../models';
import {http} from '../models';
import {context} from '../models';

export function ClearAudioCache():Promise<void>;

export function ClearLibrary():Promise<void>;

export function CloseWindow():Promise<void>;

export function CreateStreamSource(arg1:string,arg2:string,arg3:time.Time):Promise<string>;

export function CreateTheme(arg1:models.Theme):Promise<models.Theme>;

export function DeleteDownloadedSong(arg1:string):Promise<void>;

export function DeleteFavorite(arg1:string):Promise<void>;

export function DeleteSong(arg1:string):Promise<void>;

export function DeleteTheme(arg1:string):Promise<void>;

export function DeleteUnreferencedSongs():Promise<number>;

export function DownloadSong(arg1:string):Promise<string>;

export function DragWindow():Promise<void>;

export function ExportData():Promise<services.ExportData>;

export function GenerateLoginQR():Promise<services.QRCodeResponse>;

export function GetAudioCacheSize():Promise<number>;

export function GetFavoriteCollectionBVIDs(arg1:number):Promise<Array<models.BiliFavoriteInfo>>;

export function GetFavoriteCollectionInfo(arg1:number):Promise<models.BiliFavoriteCollection>;

export function GetHTTPClient():Promise<http.Client>;

export function GetImageProxyURL(arg1:string):Promise<string>;

export function GetLocalAudioURL(arg1:string):Promise<string>;

export function GetLyricMapping(arg1:string):Promise<models.LyricMapping>;

export function GetMyFavoriteCollections():Promise<Array<models.BiliFavoriteCollection>>;

export function GetPlayHistory():Promise<services.PlayHistory>;

export function GetPlayURL(arg1:string,arg2:number):Promise<services.PlayInfo>;

export function GetPlayerSetting():Promise<models.PlayerSetting>;

export function GetPlaylist():Promise<models.Playlist>;

export function GetThemes():Promise<Array<models.Theme>>;

export function GetUserInfo():Promise<services.UserInfo>;

export function ImportData(arg1:services.ExportData):Promise<void>;

export function IsLoggedIn():Promise<boolean>;

export function IsSongDownloaded(arg1:string):Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function ListFavorites():Promise<Array<models.Favorite>>;

export function ListSongs():Promise<Array<models.Song>>;

export function Logout():Promise<void>;

export function MaximizeWindow():Promise<void>;

export function MinimiseWindow():Promise<void>;

export function MinimizeToTray():Promise<void>;

export function OpenAudioCacheFolder():Promise<void>;

export function OpenDatabaseFile():Promise<void>;

export function OpenDownloadedFile(arg1:string):Promise<void>;

export function OpenDownloadsFolder():Promise<void>;

export function PollLogin(arg1:string):Promise<services.LoginPollResponse>;

export function QuitApp():Promise<void>;

export function ResolveBiliAudio(arg1:string):Promise<models.BiliAudio>;

export function SaveFavorite(arg1:models.Favorite):Promise<void>;

export function SaveLyricMapping(arg1:models.LyricMapping):Promise<void>;

export function SavePlayHistory(arg1:string,arg2:string):Promise<void>;

export function SavePlayerSetting(arg1:models.PlayerSetting):Promise<void>;

export function SavePlaylist(arg1:string,arg2:number):Promise<void>;

export function SearchBVID(arg1:string):Promise<Array<models.Song>>;

export function SearchBiliVideos(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<models.Song>>;

export function SearchLocalSongs(arg1:string):Promise<Array<models.Song>>;

export function Seed():Promise<void>;

export function SetAppContext(arg1:context.Context):Promise<void>;

export function SetCurrentTheme(arg1:string):Promise<void>;

export function UnmaximizeWindow():Promise<void>;

export function UpdateTheme(arg1:models.Theme):Promise<void>;

export function UpsertSongs(arg1:Array<models.Song>):Promise<void>;
