/**
 * 应用常量定义
 */

export const APP_VERSION = (import.meta as any).env?.VITE_APP_VERSION || 'dev';

export const DEFAULT_THEMES = [
    {
        id: 'light',
        name: '亮色',
        data: JSON.stringify({
            colorScheme: 'light',
            themeColor: '#66ccff',
            backgroundColor: '#f8fafc',
            backgroundOpacity: 1,
            backgroundBlur: 0,
            panelColor: '#ffffff',
            panelOpacity: 0.92,
            panelBlur: 0,
            panelRadius: 8,
            controlColor: '#ffffff',
            controlOpacity: 1,
            controlBlur: 0,
            textColorPrimary: '#1a1b1e',
            textColorSecondary: '#c1c2c5',
            favoriteCardColor: '#ffffff',
            cardOpacity: 1,
            componentRadius: 8,
            modalRadius: 12,
            notificationRadius: 8,
            coverRadius: 8,
            modalColor: '#ffffff',
            modalOpacity: 0.92,
            modalBlur: 0,
            windowControlsPos: 'right',
        }),
        isDefault: true,
        isReadOnly: true,
        // 以下字段用于前端显示（来自 data JSON）
        colorScheme: 'light' as const,
        themeColor: '#66ccff',
        backgroundColor: '#f8fafc',
        backgroundOpacity: 1,
        backgroundImage: '',
        backgroundBlur: 0,
        panelColor: '#ffffff',
        panelOpacity: 0.92,
        panelBlur: 0,
        panelRadius: 8,
        controlColor: '#ffffff',
        controlOpacity: 1,
        controlBlur: 0,
        textColorPrimary: '#1a1b1e',
        textColorSecondary: '#c1c2c5',
        favoriteCardColor: '#ffffff',
        cardOpacity: 1,
        componentRadius: 8,
        modalRadius: 12,
        notificationRadius: 8,
        coverRadius: 8,
        modalColor: '#ffffff',
        modalOpacity: 0.92,
        modalBlur: 0,
        windowControlsPos: 'right' as const,
    },
    {
        id: 'dark',
        name: '暗色',
        data: JSON.stringify({
            colorScheme: 'dark',
            themeColor: '#f4004f',
            backgroundColor: '#210b13ff',
            backgroundOpacity: 1,
            backgroundBlur: 0,
            panelColor: '#371f25ff',
            panelOpacity: 0.92,
            panelBlur: 0,
            panelRadius: 8,
            controlColor: '#371f25ff',
            controlOpacity: 1,
            controlBlur: 0,
            textColorPrimary: '#ffffff',
            textColorSecondary: '#a6a7ab',
            favoriteCardColor: '#371f25ff',
            cardOpacity: 1,
            componentRadius: 8,
            modalRadius: 12,
            notificationRadius: 8,
            coverRadius: 8,
            modalColor: '#371f25ff',
            modalOpacity: 0.92,
            modalBlur: 0,
            windowControlsPos: 'right',
        }),
        isDefault: true,
        isReadOnly: true,
        // 以下字段用于前端显示（来自 data JSON）
        colorScheme: 'dark' as const,
        themeColor: '#f4004f',
        backgroundColor: '#210b13ff',
        backgroundOpacity: 1,
        backgroundImage: '',
        backgroundBlur: 0,
        panelColor: '#371f25ff',
        panelOpacity: 0.92,
        panelBlur: 0,
        panelRadius: 8,
        controlColor: '#371f25ff',
        controlOpacity: 1,
        controlBlur: 0,
        textColorPrimary: '#ffffff',
        textColorSecondary: '#a6a7ab',
        favoriteCardColor: '#371f25ff',
        cardOpacity: 1,
        componentRadius: 8,
        modalRadius: 12,
        notificationRadius: 8,
        coverRadius: 8,
        modalColor: '#371f25ff',
        modalOpacity: 0.92,
        modalBlur: 0,
        windowControlsPos: 'right' as const,
    },
];

export const PLACEHOLDER_COVER = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="200" height="200"%3E%3Crect fill="%23ddd" width="200" height="200"/%3E%3Ctext fill="rgba(0,0,0,0.5)" font-family="sans-serif" font-size="30" dy="10.5" font-weight="bold" x="50%25" y="50%25" text-anchor="middle"%3E封面%3C/text%3E%3C/svg%3E';
